### ISSUE TITLE
v2.3duf

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#470]
![image](https://user-images.githubusercontent.com/38414177/223793621-958498aa-b4d1-4a3d-9293-d8bf7a7042b6.png)

cannot use connection after click on it.

**Comment by zyrrron** [comment]
testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
mouseAndKeyboardHandler.ts:248 testing up callback MouseEvent
34renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
component.ts:554 No rotation was found for component:  e
value @ component.ts:554
component.ts:554 No rotation was found for component:  e
value @ component.ts:554
component.ts:554 No rotation was found for component:  e
value @ component.ts:554
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:194:53)
    at e.<anonymous> (connectionTool.ts:81:21)
    at e.value (simpleQueue.ts:26:18)
    at o.move (connectionTool.ts:141:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
value @ renderLayer.ts:129
value @ renderLayer.ts:139
value @ connectionTool.ts:194
(anonymous) @ connectionTool.ts:81
value @ simpleQueue.ts:26
o.move @ connectionTool.ts:141
(anonymous) @ mouseAndKeyboardHandler.ts:309
component.ts:554 No rotation was found for component:  e {…}
value @ component.ts:554
value @ componentPortRenderer2D.ts:36
value @ paperComponentPortView.ts:61
value @ paperView.ts:1263
(anonymous) @ viewManager.ts:119
emit @ paper-full.js:705
setViewSize @ paper-full.js:13046
resize @ paper-full.js:12846
component.ts:554 No rotation was found for component:  e {…}
value @ component.ts:554
value @ componentPortRenderer2D.ts:36
value @ paperComponentPortView.ts:61
value @ paperView.ts:1263
(anonymous) @ viewManager.ts:119
emit @ paper-full.js:705
setViewSize @ paper-full.js:13046
resize @ paper-full.js:12846
component.ts:554 No rotation was found for component:  e {…}
value @ component.ts:554
value @ componentPortRenderer2D.ts:36
value @ paperComponentPortView.ts:61
value @ paperView.ts:1263
(anonymous) @ viewManager.ts:119
emit @ paper-full.js:705
setViewSize @ paper-full.js:13046
resize @ paper-full.js:12846
handsontable.full.min.css:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by rkrishnasanka** [comment]
The current version of `fixes/valveinsertion` partially addresses this issue of the renders breaking. We needed to add a new system for rendering channel breaks using the geometries/features with the subtract macros. The temporary fix prevents the errors that make the execution buggy. I'll merge the PR with the fix so all the features get added and tracked correctly.

**Comment by rkrishnasanka** [comment]
@zyrrron I cleaned up some of the code in the area since I couldn't actually reproduce the error. Seems like I couldn't figure out the exact actions you did before it failed.

**Comment by zyrrron** [comment]
renderLayer.ts:129 Uncaught Error: Layer does not contain a feature with the specified ID!
    at e.value (renderLayer.ts:129:55)
    at e.value (renderLayer.ts:139:14)
    at n.value (connectionTool.ts:196:69)
    at e.<anonymous> (connectionTool.ts:83:21)
    at e.value (simpleQueue.ts:26:18)
    at i.move (connectionTool.ts:143:33)
    at HTMLCanvasElement.<anonymous> (mouseAndKeyboardHandler.ts:309:17)
